In [5]:
import torch 

tensor = torch.ones(4,4)

tensor[:,1] = 0

tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [2]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [3]:
t2 = torch.cat([tensor, tensor], dim=0)
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [6]:
tensor 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [8]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [9]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [10]:
y3 = torch.rand_like(tensor)
y3

tensor([[0.4146, 0.4494, 0.3703, 0.7102],
        [0.5596, 0.1168, 0.0143, 0.7183],
        [0.5286, 0.5750, 0.5140, 0.7126],
        [0.5142, 0.6865, 0.2084, 0.1543]])

In [15]:
z1 = tensor * tensor 
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
agg = tensor.sum()
agg

tensor(12.)

In [19]:
agg_item = agg.item()
agg_item

12.0

In [20]:
tensor.add_(6)

tensor([[7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.],
        [7., 6., 7., 7.]])